// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ICw_ZSF6Of1Ems63-L4Bbdje7Nry1IY',
    appId: '1:317921097252:web:c64b80099b3e82c124cab1',
    messagingSenderId: '317921097252',
    projectId: 'saadcart-58b76',
    authDomain: 'saadcart-58b76.firebaseapp.com',
    storageBucket: 'saadcart-58b76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWm2Fks5dB22pWURNreKMDiKZ-tYGh6bA',
    appId: '1:317921097252:android:81f5c660eb6ee13c24cab1',
    messagingSenderId: '317921097252',
    projectId: 'saadcart-58b76',
    storageBucket: 'saadcart-58b76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASFhKf38tAeaVDd3sULiTeRbw2f5BYcKg',
    appId: '1:317921097252:ios:bdb1a20b03ff2c7b24cab1',
    messagingSenderId: '317921097252',
    projectId: 'saadcart-58b76',
    storageBucket: 'saadcart-58b76.appspot.com',
    iosBundleId: 'com.example.saadcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASFhKf38tAeaVDd3sULiTeRbw2f5BYcKg',
    appId: '1:317921097252:ios:bdb1a20b03ff2c7b24cab1',
    messagingSenderId: '317921097252',
    projectId: 'saadcart-58b76',
    storageBucket: 'saadcart-58b76.appspot.com',
    iosBundleId: 'com.example.saadcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ICw_ZSF6Of1Ems63-L4Bbdje7Nry1IY',
    appId: '1:317921097252:web:5e6ffcf07d89372824cab1',
    messagingSenderId: '317921097252',
    projectId: 'saadcart-58b76',
    authDomain: 'saadcart-58b76.firebaseapp.com',
    storageBucket: 'saadcart-58b76.appspot.com',
  );
}
